apiVersion: v1
kind: Service
metadata:
  name: multi-high-svc
spec:
  type: NodePort
  selector:
    app: highlighter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 31000